/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 scene.gltf -t -s 
Author: Andrea Spognetta (Spogna) (https://sketchfab.com/spogna)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/fallen-tree-1234dacf05a542c39164df00646c8b20
Title: Fallen Tree
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader"

export function FallenTree(props: any) {
	//@ts-ignore
	const { nodes, materials } = useGLTF("/fallen_tree/scene.gltf")
	return (
		<group {...props} dispose={null}>
			<group position={[10, -3, 10]} rotation={[-Math.PI / 2, 0, 0]} scale={7}>
				<mesh
					geometry={nodes.Object_2.geometry}
					material={materials.material_0}
				/>
				<mesh
					geometry={nodes.Object_3.geometry}
					material={materials.material_0}
				/>
				<mesh
					geometry={nodes.Object_4.geometry}
					material={materials.material_0}
				/>
			</group>

			<group
				position={[-10, -3, 10]}
				rotation={[-Math.PI / 2, 0, Math.PI]}
				scale={7}
			>
				<mesh
					geometry={nodes.Object_2.geometry}
					material={materials.material_0}
				/>
				<mesh
					geometry={nodes.Object_3.geometry}
					material={materials.material_0}
				/>
				<mesh
					geometry={nodes.Object_4.geometry}
					material={materials.material_0}
				/>
			</group>
		</group>
	)
}

useGLTF.preload("/fallen_tree/scene.gltf")
